######################################
spring:
  application:
    name: Spring-Data-MySql

    ############### DB Config ######################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    username: root
    password: premraj@1112
    url: jdbc:mysql://localhost:3306/employee
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
   # properties:
   #  hibernate:
   #     dialect: org.hibernate.dialect.MySQL8Dialect

