version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
   # volumes:
   #   - ./prometheus:/etc/prometheus
   #   - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
   # volumes:
   #   - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"

networks:
  default:
    name: monitoring